In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import plotly.plotly as py
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
#import matplotlib.pyplot as plt
import pylab as pl

In [2]:
df = pd.read_csv('download/IDD_18012019123152269.csv')

In [4]:
df.head(5)

,LOCATION,Country,MEASURE,Measure,AGE,Age group,DEFINITION,Definition,METHODO,Methodology,...,Year,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,AUS,Australia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2012,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.326,NaN,NaN
1,AUS,Australia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.337,NaN,NaN
2,AUS,Australia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.330,NaN,NaN
3,AUS,Australia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,...,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.315,NaN,NaN
4,AUS,Australia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,...,2008,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.336,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50439 entries, 0 to 50438
Data columns (total 21 columns):
LOCATION                 50439 non-null object
Country                  50439 non-null object
MEASURE                  50439 non-null object
Measure                  50439 non-null object
AGE                      50439 non-null object
Age group                50439 non-null object
DEFINITION               50439 non-null object
Definition               50439 non-null object
METHODO                  50439 non-null object
Methodology              50439 non-null object
TIME                     50439 non-null int64
Year                     50439 non-null int64
Unit Code                50433 non-null object
Unit                     50433 non-null object
PowerCode Code           50439 non-null int64
PowerCode                50439 non-null object
Reference Period Code    0 non-null float64
Reference Period         0 non-null float64
Value                    50439 non-null float64
Flag Codes               345 non-null object
Flags                    345 non-null object
dtypes: float64(3), int64(3), object(15)
memory usage: 8.1+ MB

In [7]:
df.describe()

,TIME,Year,PowerCode Code,Reference Period Code,Reference Period,Value
count,50439.000000,50439.000000,50439.0,0.0,0.0,5.043900e+04
mean,2009.969904,2009.969904,0.0,NaN,NaN,9.410438e+05
std,3.444818,3.444818,0.0,NaN,NaN,1.282989e+07
min,2004.000000,2004.000000,0.0,NaN,NaN,-2.813686e+06
25%,2007.000000,2007.000000,0.0,NaN,NaN,1.840000e-01
50%,2010.000000,2010.000000,0.0,NaN,NaN,8.650000e-01
75%,2013.000000,2013.000000,0.0,NaN,NaN,3.507000e+03
max,2017.000000,2017.000000,0.0,NaN,NaN,1.206910e+09

In [9]:
df.isna().sum()

LOCATION                     0
Country                      0
MEASURE                      0
Measure                      0
AGE                          0
Age group                    0
DEFINITION                   0
Definition                   0
METHODO                      0
Methodology                  0
TIME                         0
Year                         0
Unit Code                    6
Unit                         6
PowerCode Code               0
PowerCode                    0
Reference Period Code    50439
Reference Period         50439
Value                        0
Flag Codes               50094
Flags                    50094
dtype: int64

In [12]:
df_by_year = df.groupby(by='Year')
df_by_year.nunique()

,LOCATION,Country,MEASURE,Measure,AGE,Age group,DEFINITION,Definition,METHODO,Methodology,...,Year,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Year,,,,,,,,,,,,,,,,,,,,,
2004,25,25,51,51,3,3,1,1,2,2,...,1,21,21,1,1,0,0,1651,0,0
2005,25,25,51,51,3,3,1,1,2,2,...,1,20,20,1,1,0,0,1570,0,0
2006,27,27,51,51,3,3,1,1,2,2,...,1,21,21,1,1,0,0,1656,0,0
2007,27,27,51,51,3,3,1,1,2,2,...,1,20,20,1,1,0,0,1698,1,1
2008,32,32,51,51,3,3,1,1,2,2,...,1,26,26,1,1,0,0,2009,0,0
2009,35,35,51,51,3,3,1,1,2,2,...,1,29,29,1,1,0,0,2165,1,1
2010,33,33,51,51,3,3,1,1,2,2,...,1,27,27,1,1,0,0,2033,1,1
2011,37,37,51,51,3,3,1,1,2,2,...,1,31,31,1,1,0,0,2394,1,1
2012,34,34,51,51,3,3,1,1,2,2,...,1,28,28,1,1,0,0,2193,1,1
2013,33,33,51,51,3,3,1,1,2,2,...,1,27,27,1,1,0,0,2079,1,1
2014,34,34,51,51,3,3,1,1,1,1,...,1,29,29,1,1,0,0,1831,1,1
2015,34,34,51,51,3,3,1,1,1,1,...,1,28,28,1,1,0,0,1844,2,2
2016,25,25,51,51,3,3,1,1,1,1,...,1,21,21,1,1,0,0,1436,1,1
2017,1,1,49,49,3,3,1,1,1,1,...,1,9,9,1,1,0,0,90,0,0

In [67]:
df.sort_values(by='Value')

,LOCATION,Country,MEASURE,Measure,AGE,Age group,DEFINITION,Definition,METHODO,Methodology,...,Year,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
45212,KOR,Korea,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2015,KRW,Won,0,Units,NaN,NaN,-2.813686e+06,NaN,NaN
45196,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2015,KRW,Won,0,Units,NaN,NaN,-2.813686e+06,NaN,NaN
45195,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,KRW,Won,0,Units,NaN,NaN,-2.702307e+06,NaN,NaN
45211,KOR,Korea,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,KRW,Won,0,Units,NaN,NaN,-2.702307e+06,NaN,NaN
43548,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2015,KRW,Won,0,Units,NaN,NaN,-2.505898e+06,NaN,NaN
43596,KOR,Korea,TRPCTOTAL,Current transfers paid (Current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2015,KRW,Won,0,Units,NaN,NaN,-2.505898e+06,NaN,NaN
45194,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2013,KRW,Won,0,Units,NaN,NaN,-2.501364e+06,NaN,NaN
45210,KOR,Korea,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2013,KRW,Won,0,Units,NaN,NaN,-2.501364e+06,NaN,NaN
43595,KOR,Korea,TRPCTOTAL,Current transfers paid (Current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,KRW,Won,0,Units,NaN,NaN,-2.423696e+06,NaN,NaN
43547,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,KRW,Won,0,Units,NaN,NaN,-2.423696e+06,NaN,NaN
45193,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2012,KRW,Won,0,Units,NaN,NaN,-2.386956e+06,NaN,NaN
45209,KOR,Korea,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2012,KRW,Won,0,Units,NaN,NaN,-2.386956e+06,NaN,NaN
25540,ISL,Iceland,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2015,ISK,Iceland Krona,0,Units,NaN,NaN,-2.304521e+06,NaN,NaN
43546,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2013,KRW,Won,0,Units,NaN,NaN,-2.282911e+06,NaN,NaN
43594,KOR,Korea,TRPCTOTAL,Current transfers paid (Current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2013,KRW,Won,0,Units,NaN,NaN,-2.282911e+06,NaN,NaN
25406,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2015,ISK,Iceland Krona,0,Units,NaN,NaN,-2.258653e+06,NaN,NaN
43593,KOR,Korea,TRPCTOTAL,Current transfers paid (Current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2012,KRW,Won,0,Units,NaN,NaN,-2.188755e+06,NaN,NaN
43545,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2012,KRW,Won,0,Units,NaN,NaN,-2.188755e+06,NaN,NaN
26834,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,...,2011,KRW,Won,0,Units,NaN,NaN,-2.185361e+06,NaN,NaN
25539,ISL,Iceland,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,ISK,Iceland Krona,0,Units,NaN,NaN,-2.157930e+06,NaN,NaN
8029,ISL,Iceland,TRPCTOTAL,Current transfers paid (Current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2015,ISK,Iceland Krona,0,Units,NaN,NaN,-2.133335e+06,NaN,NaN
25405,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,ISK,Iceland Krona,0,Units,NaN,NaN,-2.110674e+06,NaN,NaN
7719,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2015,ISK,Iceland Krona,0,Units,NaN,NaN,-2.091417e+06,NaN,NaN
10612,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,...,2011,KRW,Won,0,Units,NaN,NaN,-2.005650e+06,NaN,NaN
8028,ISL,Iceland,TRPCTOTAL,Current transfers paid (Current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,ISK,Iceland Krona,0,Units,NaN,NaN,-2.001242e+06,NaN,NaN
26833,KOR,Korea,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,...,2010,KRW,Won,0,Units,NaN,NaN,-1.991567e+06,NaN,NaN
7718,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,ISK,Iceland Krona,0,Units,NaN,NaN,-1.960119e+06,NaN,NaN
25538,ISL,Iceland,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2013,ISK,Iceland Krona,0,Units,NaN,NaN,-1.957144e+06,NaN,NaN
25404,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2013,ISK,Iceland Krona,0,Units,NaN,NaN,-1.909592e+06,NaN,NaN
25416,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,...,2013,ISK,Iceland Krona,0,Units,NaN,NaN,-1.909270e+06,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31085,USA,United States,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,...,2008,PER,Persons,0,Units,NaN,NaN,1.918279e+08,NaN,NaN
31086,USA,United States,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,...,2009,PER,Persons,0,Units,NaN,NaN,1.932400e+08,NaN,NaN
48890,BRA,Brazil,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2009,PER,Persons,0,Units,NaN,NaN,1.939951e+08,NaN,NaN
31087,USA,United States,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,...,2010,PER,Persons,0,Units,NaN,NaN,1.944142e+08,NaN,NaN
31088,USA,United States,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,...,2011,PER,Persons,0,Units,NaN,NaN,1.964200e+08,NaN,NaN
31089,USA,United States,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,...,2012,PER,Persons,0,Units,NaN,NaN,1.970400e+08,NaN,NaN
31080,USA,United States,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2013,PER,Persons,0,Units,NaN,NaN,1.976300e+08,NaN,NaN
48891,BRA,Brazil,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2011,PER,Persons,0,Units,NaN,NaN,1.978253e+08,NaN,NaN
31081,USA,United States,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,PER,Persons,0,Units,NaN,NaN,1.996100e+08,NaN,NaN
31083,USA,United States,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2016,PER,Persons,0,Units,NaN,NaN,2.003700e+08,NaN,NaN
31082,USA,United States,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2015,PER,Persons,0,Units,NaN,NaN,2.007200e+08,NaN,NaN
48892,BRA,Brazil,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2013,PER,Persons,0,Units,NaN,NaN,2.014671e+08,NaN,NaN
49375,IND,India,HHD,Total number of households,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2011,NBR,Number,0,Units,NaN,NaN,2.543283e+08,NaN,NaN
18921,USA,United States,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,...,2005,PER,Persons,0,Units,NaN,NaN,2.936726e+08,NaN,NaN
18922,USA,United States,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,...,2008,PER,Persons,0,Units,NaN,NaN,3.013563e+08,NaN,NaN
18923,USA,United States,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,...,2009,PER,Persons,0,Units,NaN,NaN,3.041300e+08,NaN,NaN
18924,USA,United States,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,...,2010,PER,Persons,0,Units,NaN,NaN,3.059896e+08,NaN,NaN
18925,USA,United States,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,...,2011,PER,Persons,0,Units,NaN,NaN,3.086700e+08,NaN,NaN
18926,USA,United States,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,...,2012,PER,Persons,0,Units,NaN,NaN,3.109400e+08,NaN,NaN
18917,USA,United States,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2013,PER,Persons,0,Units,NaN,NaN,3.132700e+08,NaN,NaN
18918,USA,United States,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2014,PER,Persons,0,Units,NaN,NaN,3.159900e+08,NaN,NaN
18919,USA,United States,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2015,PER,Persons,0,Units,NaN,NaN,3.185800e+08,NaN,NaN
18920,USA,United States,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2016,PER,Persons,0,Units,NaN,NaN,3.200300e+08,NaN,NaN
48972,CHN,China (People's Republic of),HHD,Total number of households,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2011,NBR,Number,0,Units,NaN,NaN,3.870000e+08,NaN,NaN
49789,IND,India,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2004,PER,Persons,0,Units,NaN,NaN,5.691626e+08,NaN,NaN
49790,IND,India,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2011,PER,Persons,0,Units,NaN,NaN,7.281810e+08,NaN,NaN
49615,CHN,China (People's Republic of),IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,...,2011,PER,Persons,0,Units,NaN,NaN,7.760000e+08,NaN,NaN
49358,IND,India,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2004,PER,Persons,0,Units,NaN,NaN,9.916238e+08,NaN,NaN
48964,CHN,China (People's Republic of),IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2011,PER,Persons,0,Units,NaN,NaN,1.140000e+09,NaN,NaN
49359,IND,India,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,...,2011,PER,Persons,0,Units,NaN,NaN,1.206910e+09,NaN,NaN

In [69]:
df['MEASURE'].unique()

array(['GINI', 'CPI2010', 'PVTAA1', 'ECTOTAL', 'SECTOTAL', 'TACTOTAL',
       'INCAC1', 'INCAC2', 'PVTAA2', 'PPPPRC', 'STDG', 'INCCTOTAL',
       'GINIB', 'PVTAA3', 'SEICTOTAL', 'INCAC3', 'INCAC4', 'TRRCTOTAL',
       'PVTAA4', 'MEDIANC', 'PVTAA5', 'TRPCTOTAL', 'INCAC5', 'INCAC6',
       'PVTAA6', 'PALMA', 'PVTAA7', 'INCAC7', 'INCACTOTAL', 'PVT5B',
       'PVT5A', 'PMEAN5A', 'PVTAATOTAL', 'PVT6B', 'PVT6A', 'PMEAN6A',
       'P90P10', 'P90P50', 'P50P10', 'S80S20', 'IND', 'SHA1', 'SHA2',
       'SHA3', 'SHA4', 'SHA5', 'SHA6', 'SHA7', 'HHD', 'PVTBHTOTAL',
       'PVTAHTOTAL'], dtype=object)

In [25]:
df_by_year = df.set_index(keys='Year')
df_by_year.sort_values(by=['Year','Value'])#[['Country', 'Value']]

,LOCATION,Country,MEASURE,Measure,AGE,Age group,DEFINITION,Definition,METHODO,Methodology,TIME,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Year,,,,,,,,,,,,,,,,,,,,
2004,ISL,Iceland,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,ISK,Iceland Krona,0,Units,NaN,NaN,-1111845.0,NaN,NaN
2004,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,ISK,Iceland Krona,0,Units,NaN,NaN,-1088312.0,NaN,NaN
2004,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,2004,ISK,Iceland Krona,0,Units,NaN,NaN,-1087941.0,NaN,NaN
2004,ISL,Iceland,TRPCTOTAL,Current transfers paid (Current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,ISK,Iceland Krona,0,Units,NaN,NaN,-1020681.0,NaN,NaN
2004,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,ISK,Iceland Krona,0,Units,NaN,NaN,-1000210.0,NaN,NaN
2004,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,2004,ISK,Iceland Krona,0,Units,NaN,NaN,-999744.0,NaN,NaN
2004,ISL,Iceland,TRPCTOTAL,Current transfers paid (Current prices),OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,ISK,Iceland Krona,0,Units,NaN,NaN,-578783.0,NaN,NaN
2004,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,ISK,Iceland Krona,0,Units,NaN,NaN,-570489.0,NaN,NaN
2004,ISL,Iceland,TACTOTAL,Taxes and social security contributions paid d...,OLD,Retirement age population: above 65,CURRENT,Current definition,METH2011,Income definition until 2011,2004,ISK,Iceland Krona,0,Units,NaN,NaN,-570489.0,NaN,NaN
2004,NOR,Norway,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,NOK,Norwegian Krone,0,Units,NaN,NaN,-98441.0,NaN,NaN
2004,NOR,Norway,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,2004,NOK,Norwegian Krone,0,Units,NaN,NaN,-97674.0,NaN,NaN
2004,NOR,Norway,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,NOK,Norwegian Krone,0,Units,NaN,NaN,-95569.0,NaN,NaN
2004,SWE,Sweden,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,2004,SEK,Swedish Krona,0,Units,NaN,NaN,-90470.0,NaN,NaN
2004,NOR,Norway,TRPCTOTAL,Current transfers paid (Current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,NOK,Norwegian Krone,0,Units,NaN,NaN,-88937.0,NaN,NaN
2004,NOR,Norway,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,2004,NOK,Norwegian Krone,0,Units,NaN,NaN,-87161.0,NaN,NaN
2004,NOR,Norway,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,NOK,Norwegian Krone,0,Units,NaN,NaN,-86492.0,NaN,NaN
2004,SWE,Sweden,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,2004,SEK,Swedish Krona,0,Units,NaN,NaN,-83000.0,NaN,NaN
2004,SWE,Sweden,TACTOTAL,Taxes and social security contributions paid d...,OLD,Retirement age population: above 65,CURRENT,Current definition,METH2011,Income definition until 2011,2004,SEK,Swedish Krona,0,Units,NaN,NaN,-63354.0,NaN,NaN
2004,NOR,Norway,TRPCTOTAL,Current transfers paid (Current prices),OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,NOK,Norwegian Krone,0,Units,NaN,NaN,-48720.0,NaN,NaN
2004,NOR,Norway,TACTOTAL,Taxes and social security contributions paid d...,OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,NOK,Norwegian Krone,0,Units,NaN,NaN,-48380.0,NaN,NaN
2004,CZE,Czech Republic,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,CZK,Czech Koruna,0,Units,NaN,NaN,-43689.0,NaN,NaN
2004,CZE,Czech Republic,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,CZK,Czech Koruna,0,Units,NaN,NaN,-43019.0,NaN,NaN
2004,CZE,Czech Republic,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,2004,CZK,Czech Koruna,0,Units,NaN,NaN,-43019.0,NaN,NaN
2004,CZE,Czech Republic,TRPCTOTAL,Current transfers paid (Current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,CZK,Czech Koruna,0,Units,NaN,NaN,-37415.0,NaN,NaN
2004,CZE,Czech Republic,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,CZK,Czech Koruna,0,Units,NaN,NaN,-36856.0,NaN,NaN
2004,CZE,Czech Republic,TACTOTAL,Taxes and social security contributions paid d...,TOT,Total population,CURRENT,Current definition,METH2011,Income definition until 2011,2004,CZK,Czech Koruna,0,Units,NaN,NaN,-36856.0,NaN,NaN
2004,CAN,Canada,TRPCTOTAL,Current transfers paid (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,CAD,Canadian Dollar,0,Units,NaN,NaN,-10154.0,NaN,NaN
2004,CAN,Canada,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,2004,CAD,Canadian Dollar,0,Units,NaN,NaN,-9997.0,NaN,NaN
2004,CAN,Canada,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2004,CAD,Canadian Dollar,0,Units,NaN,NaN,-9986.0,NaN,NaN
2004,LUX,Luxembourg,TACTOTAL,Taxes and social security contributions paid d...,WA,Working age population: 18-65,CURRENT,Current definition,METH2011,Income definition until 2011,2004,EUR,Euro,0,Units,NaN,NaN,-9876.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017,CRI,Costa Rica,IND,Total number of individuals,OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,PER,Persons,0,Units,NaN,NaN,480814.0,NaN,NaN
2017,CRI,Costa Rica,SECTOTAL,Income from self-employment (current prices),OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,672258.0,NaN,NaN
2017,CRI,Costa Rica,SEICTOTAL,Income from self-employment and from goods pro...,OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,696330.0,NaN,NaN
2017,CRI,Costa Rica,TRRCTOTAL,Current transfers received (Current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,734463.0,NaN,NaN
2017,CRI,Costa Rica,SECTOTAL,Income from self-employment (current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,881796.0,NaN,NaN
2017,CRI,Costa Rica,TRRCTOTAL,Current transfers received (Current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,886302.0,NaN,NaN
2017,CRI,Costa Rica,SEICTOTAL,Income from self-employment and from goods pro...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,899293.0,NaN,NaN
2017,CRI,Costa Rica,SECTOTAL,Income from self-employment (current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,987591.0,NaN,NaN
2017,CRI,Costa Rica,SEICTOTAL,Income from self-employment and from goods pro...,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,1005210.0,NaN,NaN
2017,CRI,Costa Rica,HHD,Total number of households,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,NBR,Number,0,Units,NaN,NaN,1523869.0,NaN,NaN
2017,CRI,Costa Rica,ECTOTAL,Total earnings (current prices),OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,1765543.0,NaN,NaN
2017,CRI,Costa Rica,TRRCTOTAL,Current transfers received (Current prices),OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,2889406.0,NaN,NaN
2017,CRI,Costa Rica,IND,Total number of individuals,WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,PER,Persons,0,Units,NaN,NaN,3155339.0,NaN,NaN
2017,CRI,Costa Rica,MEDIANC,Median disposable income (current prices),OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,3321508.0,NaN,NaN
2017,CRI,Costa Rica,MEDIANC,Median disposable income (current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,3549455.0,NaN,NaN
2017,CRI,Costa Rica,ECTOTAL,Total earnings (current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,3760464.0,NaN,NaN
2017,CRI,Costa Rica,MEDIANC,Median disposable income (current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,3949312.0,NaN,NaN
2017,CRI,Costa Rica,INCAC1,Age group 0-17: mean disposable income (curren...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,4247701.0,NaN,NaN
2017,CRI,Costa Rica,ECTOTAL,Total earnings (current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,4307913.0,NaN,NaN
2017,CRI,Costa Rica,INCAC7,Age group 76+: mean disposable income (current...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,4809134.0,NaN,NaN
2017,CRI,Costa Rica,IND,Total number of individuals,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,PER,Persons,0,Units,NaN,NaN,4934743.0,NaN,NaN
2017,CRI,Costa Rica,INCCTOTAL,Mean disposable income (current prices),TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,5437760.0,NaN,NaN
2017,CRI,Costa Rica,INCACTOTAL,All age groups: mean disposable income (curren...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,5437760.0,NaN,NaN
2017,CRI,Costa Rica,INCAC2,Age group 18-25: mean disposable income (curre...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,5441175.0,NaN,NaN
2017,CRI,Costa Rica,INCCTOTAL,Mean disposable income (current prices),OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,5589675.0,NaN,NaN
2017,CRI,Costa Rica,INCAC4,Age group 41-50: mean disposable income (curre...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,5903678.0,NaN,NaN
2017,CRI,Costa Rica,INCCTOTAL,Mean disposable income (current prices),WA,Working age population: 18-65,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,5904383.0,NaN,NaN
2017,CRI,Costa Rica,INCAC3,Age group 26-40: mean disposable income (curre...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,5932272.0,NaN,NaN
2017,CRI,Costa Rica,INCAC6,Age group 66-75: mean disposable income (curre...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,6104666.0,NaN,NaN
2017,CRI,Costa Rica,INCAC5,Age group 51-65: mean disposable income (curre...,TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,CRC,Costa Rican Colon,0,Units,NaN,NaN,6256832.0,NaN,NaN

In [26]:
df.columns

Index(['LOCATION', 'Country', 'MEASURE', 'Measure', 'AGE', 'Age group',
       'DEFINITION', 'Definition', 'METHODO', 'Methodology', 'TIME', 'Year',
       'Unit Code', 'Unit', 'PowerCode Code', 'PowerCode',
       'Reference Period Code', 'Reference Period', 'Value', 'Flag Codes',
       'Flags'],
      dtype='object')

In [178]:
df_gini_countries = df_by_year[df_by_year['MEASURE']=='GINI']
df_gini_countries = df_gini_countries[(df_gini_countries['METHODO']=='METH2012') & (df_gini_countries['Age group']=='Total population')].sort_values(by=['Year','Value'])#[['Country', 'Value']]
df_gini_countries

,LOCATION,Country,MEASURE,Measure,AGE,Age group,DEFINITION,Definition,METHODO,Methodology,TIME,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Year,,,,,,,,,,,,,,,,,,,,
2004,SVN,Slovenia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.241,NaN,NaN
2004,ISL,Iceland,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.261,NaN,NaN
2004,SVK,Slovak Republic,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.265,NaN,NaN
2004,FIN,Finland,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.266,NaN,NaN
2004,CZE,Czech Republic,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.268,NaN,NaN
2004,NOR,Norway,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.285,NaN,NaN
2004,BEL,Belgium,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.287,NaN,NaN
2004,CAN,Canada,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.321,NaN,NaN
2004,IRL,Ireland,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.323,NaN,NaN
2004,ITA,Italy,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.331,NaN,NaN
2004,GRC,Greece,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.333,NaN,NaN
2004,LTU,Lithuania,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.350,NaN,NaN
2004,GBR,United Kingdom,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.354,NaN,NaN
2004,LVA,Latvia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.363,NaN,NaN
2004,PRT,Portugal,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.384,NaN,NaN
2004,IND,India,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2004,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.482,NaN,NaN
2005,SVN,Slovenia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.240,NaN,NaN
2005,CZE,Czech Republic,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.261,NaN,NaN
2005,FIN,Finland,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.265,NaN,NaN
2005,ISL,Iceland,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.273,NaN,NaN
2005,BEL,Belgium,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.277,NaN,NaN
2005,SVK,Slovak Republic,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.289,NaN,NaN
2005,CAN,Canada,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.315,NaN,NaN
2005,IRL,Ireland,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.324,NaN,NaN
2005,ITA,Italy,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.324,NaN,NaN
2005,POL,Poland,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.327,NaN,NaN
2005,GRC,Greece,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.345,NaN,NaN
2005,LTU,Lithuania,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.352,NaN,NaN
2005,GBR,United Kingdom,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.359,NaN,NaN
2005,PRT,Portugal,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2005,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.379,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,TUR,Turkey,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2015,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.404,NaN,NaN
2015,CHL,Chile,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2015,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.454,NaN,NaN
2015,CRI,Costa Rica,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2015,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.479,NaN,NaN
2015,ZAF,South Africa,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2015,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.620,P,Provisional value
2016,SVK,Slovak Republic,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.241,NaN,NaN
2016,SVN,Slovenia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.244,NaN,NaN
2016,CZE,Czech Republic,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.253,NaN,NaN
2016,FIN,Finland,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.259,NaN,NaN
2016,NOR,Norway,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.262,NaN,NaN
2016,BEL,Belgium,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.266,NaN,NaN
2016,SWE,Sweden,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.282,NaN,NaN
2016,AUT,Austria,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.284,NaN,NaN
2016,POL,Poland,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.284,NaN,NaN
2016,NLD,Netherlands,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.285,P,Provisional value
2016,FRA,France,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.291,NaN,NaN
2016,LUX,Luxembourg,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.304,NaN,NaN
2016,CAN,Canada,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.307,NaN,NaN
2016,EST,Estonia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.314,NaN,NaN
2016,ITA,Italy,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.328,NaN,NaN
2016,AUS,Australia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.330,NaN,NaN
2016,PRT,Portugal,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.331,NaN,NaN
2016,GRC,Greece,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.333,NaN,NaN
2016,ESP,Spain,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.341,NaN,NaN
2016,ISR,Israel,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.346,NaN,NaN
2016,LVA,Latvia,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.346,NaN,NaN
2016,GBR,United Kingdom,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.351,NaN,NaN
2016,LTU,Lithuania,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.378,NaN,NaN
2016,USA,United States,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.391,NaN,NaN
2016,CRI,Costa Rica,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2016,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.484,NaN,NaN
2017,CRI,Costa Rica,GINI,"Gini (disposable income, post taxes and transf...",TOT,Total population,CURRENT,Current definition,METH2012,New income definition since 2012,2017,0_TO_1,0-1 scale,0,Units,NaN,NaN,0.480,NaN,NaN

In [74]:
df_2006 = df_gini_countries.reset_index()[df_gini_countries.reset_index()['Year']==2006]
df_2006['Country']

31          Slovenia
32    Czech Republic
33           Belgium
34           Finland
35           Iceland
36            Poland
37            Canada
38           Ireland
39             Italy
40         Lithuania
41            Greece
42            Latvia
43    United Kingdom
44          Portugal
45            Brazil
Name: Country, dtype: object

In [172]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.tools as tls

tls.set_credentials_file(username='sab3r', api_key='HKmFy9ViLHOI97bG17Hq')


data = [go.Bar(
            x=df_2006['Country'],
            y=df_2006['Value']
    )]

py.iplot(data, filename='basic-bar')

In [184]:
gini_data_for_year = df_gini_countries.reset_index()[(df_gini_countries.reset_index()['Year']==int(2004))].sort_values(by='Value')
gini_data_for_year[['Country', 'Value']]

            Country  Value
0          Slovenia  0.241
1           Iceland  0.261
2   Slovak Republic  0.265
3           Finland  0.266
4    Czech Republic  0.268
5            Norway  0.285
6           Belgium  0.287
7            Canada  0.321
8           Ireland  0.323
9             Italy  0.331
10           Greece  0.333
11        Lithuania  0.350
12   United Kingdom  0.354
13           Latvia  0.363
14         Portugal  0.384
15            India  0.482

In [185]:
import plotly.plotly as py
import plotly.graph_objs as go
fig = tls.make_subplots(rows=7, cols=2)

df_poverty_list = []
traces = []
rows = [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7]
for i in range(len(years)):
    print() # col
    print() #row
    col = ((14-i)%2)+1
    year = years[i]
   # print("Year: {}, Column: {}, Row: {}".format(year, col, rows[i]))
    gini_data_for_year = df_gini_countries.reset_index()[(df_gini_countries.reset_index()['Year']==int(year))].sort_values(by='Value')
    #df2_poverty_rate_60.reset_index()[(df2_poverty_rate_60.reset_index()['Year']==int(year)) & (df2_poverty_rate_60.reset_index()['Age group'] == 'Total population')].sort_values(by='Value')
    #print("Value: {}".format(poverty_data_for_year['Value']))
    fig.append_trace(go.Bar(
        x=gini_data_for_year['Country'],
        y=gini_data_for_year['Value'],
        name=str(year)
    ), rows[i], col)


fig['layout'].update(height=1500, width=1000, title='Gini Index of Countries')
py.iplot(fig, filename='simple-subplot-with-annotations')

This is the format of your plot grid:
[ (1,1) x1,y1 ]    [ (1,2) x2,y2 ]
[ (2,1) x3,y3 ]    [ (2,2) x4,y4 ]
[ (3,1) x5,y5 ]    [ (3,2) x6,y6 ]
[ (4,1) x7,y7 ]    [ (4,2) x8,y8 ]
[ (5,1) x9,y9 ]    [ (5,2) x10,y10 ]
[ (6,1) x11,y11 ]  [ (6,2) x12,y12 ]
[ (7,1) x13,y13 ]  [ (7,2) x14,y14 ]

In [76]:
df2 = pd.read_csv('download/IDD_18012019143408574_poverty60.csv')

In [78]:
df2.describe()

,TIME,Year,PowerCode Code,Reference Period Code,Reference Period,Value
count,50439.000000,50439.000000,50439.0,0.0,0.0,5.043900e+04
mean,2009.969904,2009.969904,0.0,NaN,NaN,9.410438e+05
std,3.444818,3.444818,0.0,NaN,NaN,1.282989e+07
min,2004.000000,2004.000000,0.0,NaN,NaN,-2.813686e+06
25%,2007.000000,2007.000000,0.0,NaN,NaN,1.840000e-01
50%,2010.000000,2010.000000,0.0,NaN,NaN,8.650000e-01
75%,2013.000000,2013.000000,0.0,NaN,NaN,3.507000e+03
max,2017.000000,2017.000000,0.0,NaN,NaN,1.206910e+09

In [80]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50439 entries, 0 to 50438
Data columns (total 21 columns):
LOCATION                 50439 non-null object
Country                  50439 non-null object
MEASURE                  50439 non-null object
Measure                  50439 non-null object
AGE                      50439 non-null object
Age group                50439 non-null object
DEFINITION               50439 non-null object
Definition               50439 non-null object
METHODO                  50439 non-null object
Methodology              50439 non-null object
TIME                     50439 non-null int64
Year                     50439 non-null int64
Unit Code                50433 non-null object
Unit                     50433 non-null object
PowerCode Code           50439 non-null int64
PowerCode                50439 non-null object
Reference Period Code    0 non-null float64
Reference Period         0 non-null float64
Value                    50439 non-null float64
Flag Codes               345 non-null object
Flags                    345 non-null object
dtypes: float64(3), int64(3), object(15)
memory usage: 8.1+ MB

In [81]:
df2['MEASURE'].unique()

array(['GINI', 'CPI2010', 'PVTAA1', 'ECTOTAL', 'SECTOTAL', 'TACTOTAL',
       'INCAC1', 'INCAC2', 'PVTAA2', 'PPPPRC', 'STDG', 'INCCTOTAL',
       'GINIB', 'PVTAA3', 'SEICTOTAL', 'INCAC3', 'INCAC4', 'TRRCTOTAL',
       'PVTAA4', 'MEDIANC', 'PVTAA5', 'TRPCTOTAL', 'INCAC5', 'INCAC6',
       'PVTAA6', 'PALMA', 'PVTAA7', 'INCAC7', 'INCACTOTAL', 'PVT5B',
       'PVT5A', 'PMEAN5A', 'PVTAATOTAL', 'PVT6B', 'PVT6A', 'PMEAN6A',
       'P90P10', 'P90P50', 'P50P10', 'S80S20', 'IND', 'SHA1', 'SHA2',
       'SHA3', 'SHA4', 'SHA5', 'SHA6', 'SHA7', 'HHD', 'PVTBHTOTAL',
       'PVTAHTOTAL'], dtype=object)

In [83]:
# poverty rate before taxes and transfers poverty line 60% = PVT6B...
df2_by_year = df.set_index(keys='Year')
df2_by_year.sort_values(by=['Year','Value'], inplace=True)#[['Country', 'Value']]

In [90]:
df2_poverty_rate_60 = df2_by_year[(df2_by_year['MEASURE']=='PVT6B') & (df2_by_year['METHODO']=='METH2012')]
df2_poverty_rate_60[['Country', 'Value']].tail(5)

         Country  Value
Year
2016     Finland  0.889
2016     Belgium  0.909
2017  Costa Rica  0.272
2017  Costa Rica  0.333
2017  Costa Rica  0.563

In [100]:
print("Unique Countries, 2004-2017: {}".format(len(df2_poverty_rate_60['Country'].unique())))

Unique Countries, 2004-2017: 42

In [107]:
years = df2_poverty_rate_60.reset_index()['Year'].unique()

In [105]:
df2_poverty_rate_60.reset_index()[df2_poverty_rate_60.reset_index()['Year']==2016]

,Year,LOCATION,Country,MEASURE,Measure,AGE,Age group,DEFINITION,Definition,METHODO,...,TIME,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
858,2016,SWE,Sweden,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.167,NaN,NaN
859,2016,CZE,Czech Republic,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.195,NaN,NaN
860,2016,SVK,Slovak Republic,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.204,NaN,NaN
861,2016,AUS,Australia,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.207,NaN,NaN
862,2016,NOR,Norway,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.212,NaN,NaN
863,2016,ISR,Israel,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.224,NaN,NaN
864,2016,NLD,Netherlands,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.232,P,Provisional value
865,2016,CAN,Canada,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.236,NaN,NaN
866,2016,LVA,Latvia,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.236,NaN,NaN
867,2016,GBR,United Kingdom,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.238,NaN,NaN
868,2016,USA,United States,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.238,NaN,NaN
869,2016,EST,Estonia,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.240,NaN,NaN
870,2016,SVN,Slovenia,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.241,NaN,NaN
871,2016,AUT,Austria,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.253,NaN,NaN
872,2016,BEL,Belgium,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.254,NaN,NaN
873,2016,LTU,Lithuania,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.255,NaN,NaN
874,2016,FIN,Finland,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.264,NaN,NaN
875,2016,ITA,Italy,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.265,NaN,NaN
876,2016,PRT,Portugal,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.265,NaN,NaN
877,2016,POL,Poland,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.268,NaN,NaN
878,2016,GRC,Greece,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.278,NaN,NaN
879,2016,CRI,Costa Rica,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.278,NaN,NaN
880,2016,SWE,Sweden,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.282,NaN,NaN
881,2016,ISR,Israel,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.283,NaN,NaN
882,2016,NOR,Norway,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.287,NaN,NaN
883,2016,SVK,Slovak Republic,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.289,NaN,NaN
884,2016,AUS,Australia,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.292,NaN,NaN
885,2016,CAN,Canada,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.299,NaN,NaN
886,2016,NLD,Netherlands,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.308,P,Provisional value
887,2016,FRA,France,PVT6B,"Poverty rate before taxes and transfers, Pover...",WA,Working age population: 18-65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.308,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,2016,FIN,Finland,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.374,NaN,NaN
904,2016,ITA,Italy,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.381,NaN,NaN
905,2016,LUX,Luxembourg,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.391,NaN,NaN
906,2016,ESP,Spain,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.409,NaN,NaN
907,2016,FRA,France,PVT6B,"Poverty rate before taxes and transfers, Pover...",TOT,Total population,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.415,NaN,NaN
908,2016,ISR,Israel,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.479,NaN,NaN
909,2016,CAN,Canada,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.553,NaN,NaN
910,2016,CRI,Costa Rica,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.565,NaN,NaN
911,2016,USA,United States,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.615,NaN,NaN
912,2016,GBR,United Kingdom,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.637,NaN,NaN
913,2016,NLD,Netherlands,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.683,P,Provisional value
914,2016,AUS,Australia,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.696,NaN,NaN
915,2016,SWE,Sweden,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.704,NaN,NaN
916,2016,SVK,Slovak Republic,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.750,NaN,NaN
917,2016,POL,Poland,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.756,NaN,NaN
918,2016,LVA,Latvia,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.756,NaN,NaN
919,2016,NOR,Norway,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.759,NaN,NaN
920,2016,LTU,Lithuania,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.801,NaN,NaN
921,2016,GRC,Greece,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.804,NaN,NaN
922,2016,ITA,Italy,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.804,NaN,NaN
923,2016,EST,Estonia,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.806,NaN,NaN
924,2016,ESP,Spain,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.813,NaN,NaN
925,2016,PRT,Portugal,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.839,NaN,NaN
926,2016,SVN,Slovenia,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.840,NaN,NaN
927,2016,AUT,Austria,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.849,NaN,NaN
928,2016,FRA,France,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.865,NaN,NaN
929,2016,LUX,Luxembourg,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.870,NaN,NaN
930,2016,CZE,Czech Republic,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.876,NaN,NaN
931,2016,FIN,Finland,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.889,NaN,NaN
932,2016,BEL,Belgium,PVT6B,"Poverty rate before taxes and transfers, Pover...",OLD,Retirement age population: above 65,CURRENT,Current definition,METH2012,...,2016,RATIO,Ratio,0,Units,NaN,NaN,0.909,NaN,NaN

In [169]:
df2_poverty_rate_60.reset_index()[(df2_poverty_rate_60.reset_index()['Year']==int(2004)) & (df2_poverty_rate_60.reset_index()['Age group'] == 'Total population')].sort_values(by='Value')[['Country', 'Value']]

            Country  Value
1           Iceland  0.193
11           Norway  0.268
14            India  0.286
17           Canada  0.302
19         Slovenia  0.309
20   Czech Republic  0.316
23  Slovak Republic  0.330
24          Finland  0.336
25   United Kingdom  0.340
26          Belgium  0.348
27          Ireland  0.367
28        Lithuania  0.370
29           Greece  0.378
30         Portugal  0.394
31           Latvia  0.404
32            Italy  0.415

In [171]:
import plotly.plotly as py
import plotly.graph_objs as go
fig = tls.make_subplots(rows=7, cols=2)

df_poverty_list = []
traces = []
rows = [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7]
for i in range(len(years)):
    print() # col
    print() #row
    col = ((14-i)%2)+1
    year = years[i]
   # print("Year: {}, Column: {}, Row: {}".format(year, col, rows[i]))
    poverty_data_for_year = df2_poverty_rate_60.reset_index()[(df2_poverty_rate_60.reset_index()['Year']==int(year)) & (df2_poverty_rate_60.reset_index()['Age group'] == 'Total population')].sort_values(by='Value')
    #print("Value: {}".format(poverty_data_for_year['Value']))
    fig.append_trace(go.Bar(
        x=poverty_data_for_year['Country'],
        y=poverty_data_for_year['Value'],
        name=str(year)
    ), rows[i], col)


fig['layout'].update(height=1500, width=1000, title='Poverty Rate Before Taxes and Transfers, Poverty Line 60%')
py.iplot(fig, filename='simple-subplot-with-annotations')

This is the format of your plot grid:
[ (1,1) x1,y1 ]    [ (1,2) x2,y2 ]
[ (2,1) x3,y3 ]    [ (2,2) x4,y4 ]
[ (3,1) x5,y5 ]    [ (3,2) x6,y6 ]
[ (4,1) x7,y7 ]    [ (4,2) x8,y8 ]
[ (5,1) x9,y9 ]    [ (5,2) x10,y10 ]
[ (6,1) x11,y11 ]  [ (6,2) x12,y12 ]
[ (7,1) x13,y13 ]  [ (7,2) x14,y14 ]